### ISSUE TITLE
Update to 2.1.1

### ISSUE THREAD

**Issue by sdaves** [redgeoff/redgeoff-couchdb-docker#2]
Critical bugs have been reported in 2.1.0 and the team is suggesting an immediate update is needed:

https://blog.couchdb.org/2017/11/07/2-1-1-1-7-0/

**Comment by redgeoff** [comment]
Fixed by https://github.com/redgeoff/redgeoff-couchdb-docker/pull/3. New docker images now on docker hub as well.
