### ISSUE TITLE
Question on readme

### ISSUE THREAD

**Issue by gyetvan-andras** [redgeoff/redgeoff-couchdb-docker#4]
In the cluster sample, the line
```
./create-cluster.sh admin admin 5984 5986 "192.168.50.12 192.168.50.11"
```
shouldn't read as 
```
./create-cluster.sh admin admin 5984 5986 "192.168.50.10 192.168.50.11"
```

Use 192.168.50.10 instead of 192.168.50.12

**Comment by redgeoff** [comment]
Yes, you are correct! @gyetvan-andras would you be willing to submit a PR to fix this?

**Comment by gyetvan-andras** [comment]
Yes.

**Comment by redgeoff** [comment]
Fixed by https://github.com/redgeoff/redgeoff-couchdb-docker/pull/5
